symbols_100 =  [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK",
    "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK",
    "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "WIPRO",
    "HCLTECH", "ULTRACEMCO", "BAJFINANCE", "NESTLEIND", "TITAN",
    "TECHM", "SUNPHARMA", "ONGC", "NTPC", "POWERGRID",
    "M&M", "BAJAJFINSV", "TMPV", "TATASTEEL", "ADANIENT",
    "JSWSTEEL", "HINDALCO", "COALINDIA", "DRREDDY", "CIPLA",
    "DIVISLAB", "GRASIM", "HEROMOTOCO", "EICHERMOT", "BPCL",
    "BRITANNIA", "INDUSINDBK", "APOLLOHOSP", "TATACONSUM", "DABUR",
    "PIDILITIND", "SIEMENS", "HAVELLS", "BERGEPAINT", "GODREJCP",
    "MARICO", "MUTHOOTFIN", "BANDHANBNK", "PNB", "CANBK",
    "BANKBARODA", "LUPIN", "BIOCON", "TORNTPHARM", "IPCALAB",
    "GLAND", "ALKEM", "AUROPHARMA", "ZYDUSLIFE", "ABBOTINDIA",
    "SANOFI", "PFIZER", "GLAXO", "CHOLAFIN", "BAJAJ-AUTO",
    "TVSMOTOR", "MOTHERSON", "BOSCHLTD", "BALKRISIND", "MRF",
    "CUMMINSIND", "ABB", "BHEL", "CONCOR", "ADANIPORTS",
    "GMRAIRPORT", "IRCTC", "DMART", "NYKAA", "ETERNAL",
    "PAYTM", "POLICYBZR", "NAVINFLUOR", "SRF", "AAVAS",
    "CROMPTON", "VOLTAS", "WHIRLPOOL", "BLUESTARCO", "VGUARD",
    "HFCL", "RVNL", "IRFC", "RAILTEL", "HUDCO"
]

symbols_200 = [
        "RELIANCE","HDFCBANK","ICICIBANK","INFY","TCS","BHARTIARTL","SBIN","ITC","LT","AXISBANK",
        "KOTAKBANK","HINDUNILVR","ASIANPAINT","BAJFINANCE","MARUTI","TITAN","SUNPHARMA","ULTRACEMCO","NESTLEIND","WIPRO",
        "NTPC","POWERGRID","TECHM","ONGC","TMPV","ADANIENT","ADANIPORTS","JSWSTEEL","TATASTEEL","COALINDIA",
        "BAJAJFINSV","GRASIM","DRREDDY","CIPLA","APOLLOHOSP","DIVISLAB","EICHERMOT","HEROMOTOCO","BRITANNIA","INDUSINDBK",
        "HCLTECH","SBILIFE","HDFCLIFE","ICICIPRULI","ICICIGI","BAJAJ-AUTO","TATACONSUM","PIDILITIND","DABUR","GODREJCP",
        "MARICO","BERGEPAINT","SRF","DLF","LODHA","OBEROIRLTY","RECLTD","PFC","IRCTC","IRFC",
        "RAILTEL","HAL","BEL","BHARATFORG","ABB","SIEMENS","CUMMINSIND","BOSCHLTD","ESCORTS","ASHOKLEY",
        "TVSMOTOR","M&M","M&MFIN","CHOLAFIN","SHRIRAMFIN","LICHSGFIN","BAJAJHLDNG","INDIGO","NAUKRI","ZOMATO",
        "NYKAA","PAYTM","DMART","AVENUESUP","UBL","VBL","TRENT","ADANIGREEN","ADANIPOWER","ADANITRANS",
        "ADANIWILMAR","AMBUJACEM","ACC","RAMCOCEM","SHREECEM","JKCEMENT","ASTRAL","POLYCAB","HAVELLS","VOLTAS",
        "BLUESTAR","WHIRLPOOL","PGHH","COLPAL","NMDC","HINDZINC","VEDL","SAIL","JSL","NATIONALUM",
        "APLAPOLLO","DEEPAKNTR","PIIND","ATUL","AARTIIND","ALKEM","TORNTPHARM","LUPIN","AUROPHARMA","GLENMARK",
        "BIOCON","ZYDUSLIFE","ABBOTINDIA","GLAXO","PFIZER","LAURUSLABS","IPCALAB","METROPOLIS","LALPATHLAB","SYNGENE",
        "KIMS","FORTIS","MAXHEALTH","RAINBOW","MEDANTA","KPRMILL","PAGEIND","ARVIND","MPHASIS","COFORGE",
        "PERSISTENT","LTIM","OFSS","LTTS","MINDTREE","TATAELXSI","SONACOMS","TIINDIA","SKFINDIA","THERMAX",
        "KEI","RRKABEL","FINCABLES","CGPOWER","SCHNEIDER","INDHOTEL","LEMONTREE","CHALET","INDIAMART","JUSTDIAL",
        "DELHIVERY","BLUEDART","CONCOR","JSWINFRA","GMRINFRA","GODREJPROP","PRESTIGE","SOBHA","PHOENIXLTD","BRIGADE",
        "COROMANDEL","CHAMBLFERT","GNFC","FACT","UPL","TATACHEM","DEEPAKFERT","GUJGASLTD","IGL","MGL",
        "ATGL","PETRONET","OIL","IOC","BPCL","HPCL","GAIL","CASTROLIND","MRPL","JSWENERGY",
        "TATAPOWER","SUZLON","INOXWIND"
]

sysmbols_50 = [
    "ADANIENT","ADANIPORTS","APOLLOHOSP","ASIANPAINT","AXISBANK",
    "BAJAJ-AUTO","BAJFINANCE","BAJAJFINSV","BEL","BHARTIARTL",
    "BPCL","BRITANNIA","CIPLA","COALINDIA","DIVISLAB",
    "DRREDDY","EICHERMOT","GRASIM","HCLTECH","HDFCBANK",
    "HDFCLIFE","HEROMOTOCO","HINDALCO","HINDUNILVR","ICICIBANK",
    "INDUSINDBK","INFY","ITC","JSWSTEEL","KOTAKBANK",
    "LT","LTIM","M&M","MARUTI","NESTLEIND",
    "NTPC","ONGC","POWERGRID","RELIANCE","SBILIFE",
    "SBIN","SUNPHARMA","TATACONSUM","TATAMOTORS","TATASTEEL",
    "TCS","TECHM","TITAN","ULTRACEMCO","WIPRO"
]